/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package galpon.ui.ventas;

import galpon.bd.conection.Conexion;
import galpon.model.bd.query.fCliente;
import galpon.model.bd.query.fContar;
import galpon.model.bd.query.ProductoModel;
import galpon.model.bd.query.fVenta;
import galpon.ui.styles.estiloTabla;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import galpon.model.dto.mProducto;
import galpon.model.dto.mVenta;
import galpon.model.bd.query.fCargarCombo;

/**
 *
 * @author GIMORE
 */
public class VentasForm extends javax.swing.JInternalFrame {

    private Conexion postsql = new Conexion();
    private Connection cn = null; //variable de conexion de sql
    // private Connection cn = postsql.conectar();
    private String sSQL = "";//para almacenar cadena de sql    

    /**
     * Creates new form frmVenta
     */
    public VentasForm() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        mostrar("");
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));//fondo blanco detras de la tabla
        jScrollPane3.getViewport().setBackground(new java.awt.Color(255, 255, 255));//fondo blanco detras de la tabla
        //cargarCombos();
        estiloTabla diseño = new estiloTabla();
        diseño.tabla(tablaVentas);
        diseño.tabla(tablaProducto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSelProducto = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnSelCliente = new javax.swing.JButton();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AtxtDescripcion = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell

            };
        };
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell

            };
        };
        jPanel4 = new javax.swing.JPanel();
        lblidVenta = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(9, 66, 66));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTROL DE VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(311, 311, 311))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(9, 66, 66));
        jPanel3.setPreferredSize(new java.awt.Dimension(252, 503));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRODUCTO");

        btnSelProducto.setText("AGREGAR PRODUCTO +");
        btnSelProducto.setEnabled(false);
        btnSelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelProductoMouseClicked(evt);
            }
        });
        btnSelProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/addverde32px.png"))); // NOI18N
        btnNuevaVenta.setText("INICIAR VENTA");
        btnNuevaVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(9, 66, 66));
        jLabel8.setText("Cliente");

        txtCliente.setEnabled(false);
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        btnSelCliente.setText("+");
        btnSelCliente.setEnabled(false);
        btnSelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelClienteActionPerformed(evt);
            }
        });

        jDateFecha.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(9, 66, 66));
        jLabel5.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(9, 66, 66));
        jLabel6.setText("Descripcion");

        AtxtDescripcion.setColumns(10);
        AtxtDescripcion.setLineWrap(true);
        AtxtDescripcion.setRows(1);
        AtxtDescripcion.setTabSize(1);
        AtxtDescripcion.setEnabled(false);
        AtxtDescripcion.setName(""); // NOI18N
        AtxtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AtxtDescripcionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(AtxtDescripcion);

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "UNI. MEDIDA", "PRECIO", "TOTAL"
            }
        ));
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaProducto);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Venta", "Producto", "Cantidad", "Fecha", "Uni. Medida", "Precio Uni. Medida", "Descripcion", "Total Venta"
            }
        ));
        tablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVentas);

        jPanel4.setBackground(new java.awt.Color(9, 66, 66));

        lblidVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblidVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblidVenta.setText("#");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/searchblanco32px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblidVenta)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/editverde32px.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSelCliente)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(btnSelCliente))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrar(String buscar) { //para mostrar registros de la tabla galpon
        DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente       
        try {
            fVenta func = new fVenta();
            modelo = func.mostrar(buscar);
            tablaVentas.setModel(modelo);
            // return modelo;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            // return null;
        }
    }    // cierre de metodo mostrar

    /* private void cargarCombos() {// carga datos de la BD y los pone en los combobox
      
        comboProducto.removeAllItems();
        comboProducto.addItem("Seleccionar");
       fCargarCombo consulta = new fCargarCombo();
        ArrayList<String> listaProducto = new ArrayList<String>();
        listaProducto = consulta.llenar_combo("nombre_producto", "producto") ;        
        for (int i = 0; i < listaProducto.size(); i++) {
            comboProducto.addItem(listaProducto.get(i));
        }    
    }
     */
    private void habilitarcampos() {
        //txtIdVenta.setEnabled(true);
        btnSelProducto.setEnabled(true);
        btnSelCliente.setEnabled(true);
        // comboProducto.setEnabled(true);       
        txtCliente.setEnabled(true);
        jDateFecha.setEnabled(true);
        AtxtDescripcion.setEnabled(true);
    }

    private void deshabilitarcampos() {
        lblidVenta.setEnabled(false);
        btnSelProducto.setEnabled(false);
        btnSelCliente.setEnabled(false);
        //comboProducto.setEnabled(false);      
        txtCliente.setEnabled(false);
        jDateFecha.setEnabled(false);
        AtxtDescripcion.setEnabled(false);
          DefaultTableModel modelo = (DefaultTableModel) tablaProducto.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        fContar contar = new fContar();
        try {
            if (contar.existencia("id_producto", "producto") == 0) {//verifica si hay productos para venta
                JOptionPane.showMessageDialog(rootPane, "No existen Productos registrados para la Venta");
                return;
            }
        } catch (Exception e) {
        }
        ProductoModel validar = new ProductoModel();
        if (validar.contar_stock() == 0) {
            JOptionPane.showMessageDialog(null, " No hay ningun producto en el Stock de ventas");
            return;
        }
        fCliente funcC = new fCliente();

        if (btnNuevaVenta.getText().equals("INICIAR VENTA")) {
            habilitarcampos();
            try {
                if (funcC.contar("cliente") == 0) {
                    txtCliente.setEnabled(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(VentasForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            lblidVenta.setText("");
//            comboProducto.setSelectedItem("Seleccionar");           
            Calendar actual = new GregorianCalendar();
            jDateFecha.setCalendar(actual);
            AtxtDescripcion.setText("");
            btnNuevaVenta.setLabel("PROCESAR");
            btnEditar.setLabel("CANCELAR");
            btnEditar.setIcon(new ImageIcon("src/Archivos/cancelverde32px.png"));
            btnEditar.setEnabled(true);
            return;
        }

        mVenta datos = new mVenta();
        fVenta func = new fVenta();
        /* ------------------------------------------------------------------------*/
        if (btnNuevaVenta.getText().equals("PROCESAR")) {
//            if (comboProducto.getSelectedItem().equals("Seleccionar")) {
//                JOptionPane.showMessageDialog(null, "Selecciona un Producto");
//                return;
//            }

            if (jDateFecha.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Ingresa una Fecha");
                return;
            }
            java.util.Date fecha = jDateFecha.getDate();//almacena la fecha en formato Date
            long fechaV = fecha.getTime();
            java.sql.Date fechaVenta = new java.sql.Date(fechaV);//establece el formato compatible con sql
            //datos.setCantidad(Integer.parseInt(txtCantidad.getText()));
            datos.setDescripcion(AtxtDescripcion.getText());
            datos.setFecha(fechaVenta.toString());

            //viendo la cantidad disponible para la venta        
            //JOptionPane.showMessageDialog(null,func.verCantidad(comboProducto.getSelectedItem().toString()));  
            fContar func2 = new fContar();
            // int disponible = func2.Contabilizar("\"producto\" where \"nombre_producto\" = '" + comboProducto.getSelectedItem().toString() + "'");
//            if (disponible < Integer.parseInt(txtCantidad.getText())) {
//                JOptionPane.showMessageDialog(null, "Solo hay Disponible para la venta : " + disponible);
//                return;
//            }
//
//            if (!func.insertar(datos, comboProducto.getSelectedItem().toString(), frmInicio.lbluser.getText(), txtCliente.getText())) {
//                JOptionPane.showMessageDialog(rootPane, "ERROR al Realizar venta");
//                return;
//            }
            mProducto dato = new mProducto();
            //dato.setIdProducto(disponible);// ajustando para que actualice 
            //    dato.setNombre(comboProducto.getSelectedItem().toString());
            //  dato.setStock(disponible - Integer.parseInt(txtCantidad.getText()));
            validar.editarStock(dato);
            //insertar(comboProducto.getSelectedItem().toString(), Integer.parseInt(txtCantidad.getText()));
            mostrar("");
            lblidVenta.setText("");
            // comboProducto.setSelectedItem("Seleccionar");
            //  txtCantidad.setText("");
            jDateFecha.setDate(null);
            AtxtDescripcion.setText("");
            btnNuevaVenta.setText("INICIAR VENTA");
            btnEditar.setEnabled(false);
            btnEditar.setText("EDITAR");
            deshabilitarcampos();
            return;
        }
        if (btnNuevaVenta.getText().equals("ACTUALIZAR")) {
            java.util.Date fecha = jDateFecha.getDate();//almacena la fecha en formato Date
            long fechaV = fecha.getTime();
            java.sql.Date fechaVenta = new java.sql.Date(fechaV);//establece el formato compatible con sql

            // datos.setCantidad(Integer.parseInt(txtCantidad.getText()));
            datos.setDescripcion(AtxtDescripcion.getText());
            datos.setIdVenta(Integer.parseInt(lblidVenta.getText()));
            datos.setFecha(fechaVenta.toString());
//            if (func.editar(datos, comboProducto.getSelectedItem().toString())) {
//                JOptionPane.showMessageDialog(rootPane, " Datos de venta Editados correctamente ");
//            }
            //editar(txtIdVenta.getText(), comboProducto.getSelectedItem().toString());
            btnNuevaVenta.setText("INICIAR VENTA");
            btnEditar.setEnabled(false);
            btnEditar.setText("EDITAR");
            mostrar("");
            deshabilitarcampos();
        }

    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // 
        if (btnEditar.getLabel().equals("CANCELAR")) {
            deshabilitarcampos();
            btnNuevaVenta.setLabel("INICIAR VENTA");
            btnNuevaVenta.setIcon(new ImageIcon("src/Archivos/addverde32px.png"));
            btnEditar.setLabel("EDITAR");
            btnEditar.setIcon(new ImageIcon("src/Archivos/editverde32px.png"));
            btnEditar.setEnabled(false);
            jDateFecha.setCalendar(null);
        } else {
            habilitarcampos();
            btnNuevaVenta.setLabel("ACTUALIZAR");
            btnEditar.setLabel("CANCELAR");
            btnEditar.setIcon(new ImageIcon("src/Archivos/cancelverde32px.png"));
            btnNuevaVenta.setIcon(new ImageIcon("src/Archivos/saveverde32px.png"));
            btnEditar.setEnabled(true);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void tablaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentasMouseClicked
        // acciones al dar clic sobre la tabla ventas
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date fecha;
        int filaSel = tablaVentas.rowAtPoint(evt.getPoint());// guarda en la variable filaSel la ila que se selecciono en la tabla
        btnEditar.setEnabled(true);
        lblidVenta.setText(tablaVentas.getValueAt(filaSel, 0).toString());
        AtxtDescripcion.setText(tablaVentas.getValueAt(filaSel, 6).toString());
        //  comboProducto.setSelectedItem(tablaVentas.getValueAt(filaSel, 1).toString());
        // txtCantidad.setText(tablaVentas.getValueAt(filaSel, 2).toString());
        try {
            fecha = formatoFecha.parse((String) tablaVentas.getValueAt(filaSel, 3));
            jDateFecha.setDate(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(VentasForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        // txtCantidad.setText(tablaVentas.getValueAt(filaSel, 2).toString());
    }//GEN-LAST:event_tablaVentasMouseClicked

    private void AtxtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AtxtDescripcionKeyTyped
        // TODO add your handling code here:
        if (AtxtDescripcion.getText().length() == 100) {//para que el maximo de caracteres ingresados sea 100
            evt.consume();
        }
    }//GEN-LAST:event_AtxtDescripcionKeyTyped

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        // txtNumGalpon.setText("");
        mostrar(txtBuscar.getText());
        //dimensioncols();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnSelProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelProductoActionPerformed
        // TODO add your handling code here:
        new galpon.ui.ventas.VentaProductosDialog(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnSelProductoActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteKeyTyped

    private void btnSelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelClienteActionPerformed
        // TODO add your handling code here:
        new galpon.ui.ventas.VentaClienteDialog(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnSelClienteActionPerformed

    private void tablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaProductoMouseClicked

    private void btnSelProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AtxtDescripcion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnSelCliente;
    private javax.swing.JButton btnSelProducto;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblidVenta;
    public static javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtBuscar;
    public static javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables

}
