/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Consultas.fGalpon;
import Estilos.estiloTabla;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

/**
 *
 * @author GIMORE
 */
public class FrmGalponEnSal extends javax.swing.JInternalFrame {

    private Conexion postsql = new Conexion();
    private Connection cn = null; //variable de conexion de sql
    // private Connection cn = postsql.conectar();
    private String sSQL = "";//para almacenar cadena de conexion 
    public static String accion = ""; //para determinar la accion en la ventana entradas - salidas de aves
    public static String[] datostabla = new String[7];

    /**
     * Creates new form frmGalpon
     */
    public FrmGalponEnSal() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        estiloTabla diseño = new estiloTabla();
        diseño.tabla(tablaSalida);
        diseño.tabla(tablaEntrada);
        //this.setExtendedState(MAXIMIZED_BOTH);//maximizar el formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblGalpon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNoGalpon = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNuevaEntrada = new javax.swing.JButton();
        btnEditarEnt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnNuevaSalida = new javax.swing.JButton();
        btnEditarSal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntrada = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSalida = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(9, 66, 66));

        lblGalpon.setForeground(new java.awt.Color(255, 255, 255));
        lblGalpon.setText("GALPON N° ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("CONTROL DE BAJAS / ALTAS");

        lblNoGalpon.setForeground(new java.awt.Color(255, 255, 255));
        lblNoGalpon.setText("00");

        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setText("###");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALDO DE AVES ACTUAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(370, 370, 370)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSaldo)
                .addGap(30, 30, 30)
                .addComponent(lblGalpon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNoGalpon)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGalpon)
                    .addComponent(lblNoGalpon)
                    .addComponent(lblSaldo)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(9, 66, 66));

        btnNuevaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevaEntrada.setForeground(new java.awt.Color(9, 66, 66));
        btnNuevaEntrada.setText("NUEVA");
        btnNuevaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaEntradaActionPerformed(evt);
            }
        });

        btnEditarEnt.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarEnt.setForeground(new java.awt.Color(9, 66, 66));
        btnEditarEnt.setText("EDITAR");
        btnEditarEnt.setEnabled(false);
        btnEditarEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(9, 66, 66));

        btnNuevaSalida.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevaSalida.setForeground(new java.awt.Color(9, 66, 66));
        btnNuevaSalida.setText("NUEVA");
        btnNuevaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaSalidaActionPerformed(evt);
            }
        });

        btnEditarSal.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarSal.setForeground(new java.awt.Color(9, 66, 66));
        btnEditarSal.setText("EDITAR");
        btnEditarSal.setEnabled(false);
        btnEditarSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarSal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarSal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        tablaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo de Ave", "Fecha de Apertura", "Saldo", "F. Entrada", "Cantidad Entrante", "Descripcion Entrada", "ID"
            }
        ));
        tablaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEntradaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEntrada);

        jLabel2.setForeground(new java.awt.Color(9, 66, 66));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HISTORIAL DE ENTRADAS");

        lblEntrada.setText("idEntrada");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntrada)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo de Ave", "Fecha de Apertura", "Saldo", "F. Salida", "Cantidad Saliente", "Descripcion Salida", "ID"
            }
        ));
        tablaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaSalida);

        jLabel7.setForeground(new java.awt.Color(9, 66, 66));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HISTORIAL DE SALIDAS");

        lblSalida.setText("idSalida");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalida)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void frmGalpon(String galpon) {
        String saldo = "";
        lblNoGalpon.setText(galpon);
        mostrarEntrada(galpon);
        mostrarSalida(galpon);
        try {
            fGalpon func = new fGalpon();
            saldo = func.contar(Integer.parseInt(galpon));
        } catch (SQLException ex) {
            Logger.getLogger(FrmGalponEnSal.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblSaldo.setText(saldo);
        
    }

    public void mostrarEntrada(String buscar) { //para mostrar registros de la tabla galpon

        //  DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente
      
        try {
            DefaultTableModel modelo;
            fGalpon func = new fGalpon();
            modelo = func.mostrarEntrada(buscar);
            tablaEntrada.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           }    // cierre de metodo

    // mostrar las salidas   
    public void mostrarSalida(String buscar) { //para mostrar registros de la tabla galpon
        // DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente
              try {
            DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente
            fGalpon func = new fGalpon();
            modelo = func.mostrarSalida(buscar);
            tablaSalida.setModel(modelo);
        } catch (Exception e) {
        }
     
    }    // cierre de metodo


    private void btnNuevaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaEntradaActionPerformed
        accion = "nueva entrada";
        DiagGalponEnSal ensal = new DiagGalponEnSal(new JFrame(), true);
        ensal.lblTitulo.setText("NUEVO INGRESO DE AVES");
        ensal.setVisible(true);
        btnEditarEnt.setEnabled(false);
        btnEditarSal.setEnabled(false);
        frmGalpon(lblNoGalpon.getText());//para recargar el formulario

    }//GEN-LAST:event_btnNuevaEntradaActionPerformed

    private void btnEditarEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEntActionPerformed

        accion = "editar entrada";
        DiagGalponEnSal ensal = new DiagGalponEnSal(new JFrame(), true);
        ensal.lblTitulo.setText("EDITAR REGISTRO DE ENTRADA");
        ensal.setVisible(true);
        btnEditarEnt.setEnabled(false);
        btnEditarSal.setEnabled(false);
        frmGalpon(lblNoGalpon.getText());//para recargar el formulario

    }//GEN-LAST:event_btnEditarEntActionPerformed

    private void btnNuevaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSalidaActionPerformed
        // 
        accion = "nueva salida";
        DiagGalponEnSal ensal = new DiagGalponEnSal(new JFrame(), true);
        ensal.lblTitulo.setText("NUEVO REPORTE DE BAJAS DE AVES");
        ensal.setVisible(true);
        btnEditarEnt.setEnabled(false);
        btnEditarSal.setEnabled(false);
        frmGalpon(lblNoGalpon.getText());//para recargar el formulario

    }//GEN-LAST:event_btnNuevaSalidaActionPerformed

    private void btnEditarSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSalActionPerformed
        //
        accion="editar salida";
        DiagGalponEnSal ensal = new DiagGalponEnSal(new JFrame(),true);
         ensal.lblTitulo.setText("EDITAR REPORTE DE BAJAS DE AVES");      
        ensal.setVisible(true);
         btnEditarEnt.setEnabled(false);
        btnEditarSal.setEnabled(false);      
        
    }//GEN-LAST:event_btnEditarSalActionPerformed

    private void tablaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEntradaMouseClicked
        // TODO add your handling code here:

        int filaSel = tablaEntrada.rowAtPoint(evt.getPoint());
        datostabla[0] = tablaEntrada.getValueAt(filaSel, 0).toString();
        datostabla[1] = tablaEntrada.getValueAt(filaSel, 1).toString();
        datostabla[2] = tablaEntrada.getValueAt(filaSel, 2).toString();
        datostabla[3] = tablaEntrada.getValueAt(filaSel, 3).toString();
        datostabla[4] = tablaEntrada.getValueAt(filaSel, 4).toString();
        datostabla[5] = tablaEntrada.getValueAt(filaSel, 5).toString();
        datostabla[6] = tablaEntrada.getValueAt(filaSel, 6).toString();
        btnEditarEnt.setEnabled(true);
    }//GEN-LAST:event_tablaEntradaMouseClicked

    private void tablaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidaMouseClicked
        // TODO add your handling code here:
        int filaSel = tablaSalida.rowAtPoint(evt.getPoint());

        datostabla[0] = tablaEntrada.getValueAt(filaSel, 0).toString();
        datostabla[1] = tablaEntrada.getValueAt(filaSel, 1).toString();
        datostabla[2] = tablaEntrada.getValueAt(filaSel, 2).toString();
        datostabla[3] = tablaEntrada.getValueAt(filaSel, 3).toString();
        datostabla[4] = tablaEntrada.getValueAt(filaSel, 4).toString();
        datostabla[5] = tablaEntrada.getValueAt(filaSel, 5).toString();
        datostabla[6] = tablaEntrada.getValueAt(filaSel, 6).toString();

        //txtFechaSal.setText(tablaSalida.getValueAt(filaSel, 3).toString());
        btnEditarSal.setEnabled(true);
    }//GEN-LAST:event_tablaSalidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGalponEnSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGalponEnSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGalponEnSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGalponEnSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGalponEnSal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarEnt;
    private javax.swing.JButton btnEditarSal;
    private javax.swing.JButton btnNuevaEntrada;
    private javax.swing.JButton btnNuevaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblGalpon;
    private javax.swing.JLabel lblNoGalpon;
    public static javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JTable tablaEntrada;
    private javax.swing.JTable tablaSalida;
    // End of variables declaration//GEN-END:variables
}
