/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Funciones.fAdminGalpon;
import Funciones.fGalpon;
import Interfaz.diseño.estiloTabla;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.mEntrada;
import modelos.mSalida;

/**
 *
 * @author GIMORE
 */
public class frmGalpon extends javax.swing.JInternalFrame {

    private Conexion postsql = new Conexion();
    private Connection cn = null; //variable de conexion de sql
    // private Connection cn = postsql.conectar();
    private String sSQL = "";//para almacenar cadena de conexion 

    /**
     * Creates new form frmGalpon
     */
    public frmGalpon() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        estiloTabla diseño = new estiloTabla();
        diseño.tabla(tablaSalida);
        diseño.tabla(tablaEntrada);
        //this.setExtendedState(MAXIMIZED_BOTH);//maximizar el formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblGalpon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNoGalpon = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNuevaEntrada = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadEnt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEditarEnt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        AtxtDescripcionEnt = new javax.swing.JTextArea();
        jDateFechaEnt = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        btnNuevaSalida = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCantidadSal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnEditarSal = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        AtxtDescripcionSal = new javax.swing.JTextArea();
        jDateFechaSal = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntrada = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSalida = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(9, 66, 66));

        lblGalpon.setForeground(new java.awt.Color(255, 255, 255));
        lblGalpon.setText("GALPON N° ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Control de Entradas / Salidas");

        lblNoGalpon.setForeground(new java.awt.Color(255, 255, 255));
        lblNoGalpon.setText("####");

        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setText("###");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saldo Actual :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSaldo)
                .addGap(18, 18, 18)
                .addComponent(lblGalpon)
                .addGap(18, 18, 18)
                .addComponent(lblNoGalpon)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGalpon)
                        .addComponent(lblNoGalpon)
                        .addComponent(lblSaldo)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(9, 66, 66));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)), "Registrar Entrada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnNuevaEntrada.setText("Nueva");
        btnNuevaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaEntradaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha");

        txtCantidadEnt.setEnabled(false);
        txtCantidadEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadEntActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripcion");

        btnEditarEnt.setText("Editar");
        btnEditarEnt.setEnabled(false);
        btnEditarEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEntActionPerformed(evt);
            }
        });

        jScrollPane3.setEnabled(false);

        AtxtDescripcionEnt.setColumns(20);
        AtxtDescripcionEnt.setRows(5);
        jScrollPane3.setViewportView(AtxtDescripcionEnt);

        jDateFechaEnt.setDateFormatString("dd-MM-yyyy");
        jDateFechaEnt.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtCantidadEnt, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jDateFechaEnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(btnEditarEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaEntrada)
                    .addComponent(btnEditarEnt))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateFechaEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(9, 66, 66));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Salida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnNuevaSalida.setText("Nueva");
        btnNuevaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaSalidaActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad");

        txtCantidadSal.setEnabled(false);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descripcion");

        btnEditarSal.setText("Editar");
        btnEditarSal.setEnabled(false);
        btnEditarSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSalActionPerformed(evt);
            }
        });

        AtxtDescripcionSal.setColumns(20);
        AtxtDescripcionSal.setRows(5);
        jScrollPane4.setViewportView(AtxtDescripcionSal);

        jDateFechaSal.setDateFormatString("dd-MM-yyyy");
        jDateFechaSal.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(btnEditarSal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadSal, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jDateFechaSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaSalida)
                    .addComponent(btnEditarSal))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jDateFechaSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        tablaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo de Ave", "Fecha de Apertura", "Saldo", "F. Entrada", "Cantidad Entrante", "Descripcion Entrada", "ID"
            }
        ));
        tablaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEntradaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEntrada);

        jLabel2.setForeground(new java.awt.Color(9, 66, 66));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HISTORIAL DE ENTRADAS");

        lblEntrada.setText("idEntrada");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntrada)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntrada)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo de Ave", "Fecha de Apertura", "Saldo", "F. Salida", "Cantidad Saliente", "Descripcion Salida", "ID"
            }
        ));
        tablaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaSalida);

        jLabel7.setForeground(new java.awt.Color(9, 66, 66));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HISTORIAL DE SALIDAS");

        lblSalida.setText("idSalida");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalida)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void frmGalpon(String galpon) {
        String saldo = "";
        lblNoGalpon.setText(galpon);
        mostrarEntrada(galpon);
        mostrarSalida(galpon);
        try {
            fGalpon func = new fGalpon();
            saldo = func.contar(Integer.parseInt(galpon));
        } catch (SQLException ex) {
            Logger.getLogger(frmGalpon.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblSaldo.setText(saldo);
        //mostrarEntrada(galpon);
    }

    public void mostrarEntrada(String buscar) { //para mostrar registros de la tabla galpon

        //  DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente
        cn = postsql.conectar(); // asigna la cadena de conexion a la variable de conexion SQL
        if (cn == null) { // confirma si no hay conexion de la BD para no proceder con las consultas..
            JOptionPane.showMessageDialog(rootPane, " No se pueden  cargar Registros \n"
                    + " debido a un problema de Conexion a la BD. ");
            return;
        }

        try {
            DefaultTableModel modelo;
            fGalpon func = new fGalpon();
            modelo = func.mostrarEntrada(buscar);
            tablaEntrada.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        postsql.cierraConexion();
    }    // cierre de metodo

    // mostrar las salidas   
    public void mostrarSalida(String buscar) { //para mostrar registros de la tabla galpon
        // DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente
        cn = postsql.conectar(); // asigna la cadena de conexion a la variable de conexion SQL

        try {
            DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente
            fGalpon func = new fGalpon();
            modelo = func.mostrarSalida(buscar);
            tablaSalida.setModel(modelo);
        } catch (Exception e) {
        }

        postsql.cierraConexion();
    }    // cierre de metodo

    // Habilitar o deshabilitar campos de la Entrada
    private void habilitarcamposEnt() {
        jDateFechaEnt.setEnabled(true);
        txtCantidadEnt.setEnabled(true);
        AtxtDescripcionEnt.setEnabled(true);

    }

    private void deshabilitarcamposEnt() {
        jDateFechaEnt.setEnabled(false);
        txtCantidadEnt.setEnabled(false);
        AtxtDescripcionEnt.setEnabled(false);

    }

    // Habilitar o deshabilitar campos de la Salida
    private void habilitarcamposSal() {
        jDateFechaSal.setEnabled(true);
        txtCantidadSal.setEnabled(true);
        AtxtDescripcionSal.setEnabled(true);

    }

    private void deshabilitarcamposSal() {
        jDateFechaSal.setEnabled(false);
        txtCantidadSal.setEnabled(false);
        AtxtDescripcionSal.setEnabled(false);

    }

    private void txtCantidadEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEntActionPerformed

    private void btnNuevaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaEntradaActionPerformed
        // habilitar campos

        if (btnNuevaEntrada.getText().equals("Nueva")) {
            btnNuevaEntrada.setLabel("Guardar");
            btnEditarEnt.setLabel("Cancelar");
            btnEditarEnt.setEnabled(true);
            txtCantidadEnt.setText("");
            Calendar actual = new GregorianCalendar();
            jDateFechaEnt.setCalendar(actual);
            habilitarcamposEnt();
            // jDateFecha.requestFocus();
            return;
        }

        mEntrada datosEnt = new mEntrada();
        fGalpon func = new fGalpon();

        if (btnNuevaEntrada.getText().equals("Guardar")) {

            if (jDateFechaEnt.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Debes asignar una fecha de Entrada");
                jDateFechaEnt.requestFocus();
                return;
            }
            if (txtCantidadEnt.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debes asignar una Cantidad");
                txtCantidadEnt.requestFocus();
                return;
            }
            Date dateEnt = jDateFechaEnt.getDate();//almacena la fecha en formato Date
            long fechaE = dateEnt.getTime();
            java.sql.Date fechaEnt = new java.sql.Date(fechaE);//establece el formato compatible con sql

            datosEnt.setIdGalpon(Integer.parseInt(lblNoGalpon.getText()));
            datosEnt.setFecha(fechaEnt.toString());
            datosEnt.setCantidad(Integer.parseInt(txtCantidadEnt.getText()));
            datosEnt.setDescripcion(AtxtDescripcionEnt.getText());
            datosEnt.sethSaldo(Integer.parseInt(lblSaldo.getText()));
            func.insertarEntrada(datosEnt);// ejecuta la insercion de datos

//insertar(lblNoGalpon.getText(), "Entrada");//envia el numero del galpon, envia el tipo de movimiento (entrada-salida)
            btnNuevaEntrada.setLabel("Nueva");
            btnEditarEnt.setLabel("Editar");
            btnEditarEnt.setEnabled(false);
            txtCantidadEnt.setText("");
            //jDateFecha.setDateFormatString("");
            deshabilitarcamposEnt();
            frmGalpon(lblNoGalpon.getText());//para recargar el formulario
            mostrarEntrada(lblNoGalpon.getText());
            mostrarSalida(lblNoGalpon.getText());

            fAdminGalpon func2 = new fAdminGalpon();
            func2.listar("");
            return;

        }

        if (btnNuevaEntrada.getText().equals("Actualizar")) {
            Date dateEnt = jDateFechaEnt.getDate();//almacena la fecha en formato Date
            long fechaE = dateEnt.getTime();
            java.sql.Date fechaEnt = new java.sql.Date(fechaE);//establece el formato compatible con sql

            datosEnt.setIdGalpon(Integer.parseInt(lblNoGalpon.getText()));
            datosEnt.setFecha(fechaEnt.toString());
            datosEnt.setCantidad(Integer.parseInt(txtCantidadEnt.getText()));
            datosEnt.setDescripcion(AtxtDescripcionEnt.getText());
            datosEnt.sethSaldo(Integer.parseInt(lblSaldo.getText()));
            datosEnt.setIdEntrada(Integer.parseInt(lblEntrada.getText()));
            func.editarEntrada(datosEnt);
            // editar(lblNoGalpon.getText(), lblEntrada.getText(), "entrada");//envia el numero del galpon, envia el ID de la entrada
            btnNuevaEntrada.setLabel("Nueva");
            btnEditarEnt.setLabel("Editar");
            txtCantidadEnt.setText("");
            //jDateFecha.setDateFormatString("");
            deshabilitarcamposEnt();
            frmGalpon(lblNoGalpon.getText());
            mostrarEntrada(lblNoGalpon.getText());

            mostrarSalida(lblNoGalpon.getText());

        }


    }//GEN-LAST:event_btnNuevaEntradaActionPerformed

    private void btnEditarEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEntActionPerformed
        // 

        if (btnEditarEnt.getLabel().equals("Cancelar")) {
            deshabilitarcamposEnt();
            btnNuevaEntrada.setLabel("Nueva");
            btnEditarEnt.setLabel("Editar");
            btnEditarEnt.setEnabled(false);
            jDateFechaEnt.setCalendar(null);
        } else {
            habilitarcamposEnt();
            txtCantidadEnt.requestFocus();
            btnNuevaEntrada.setLabel("Actualizar");
            btnEditarEnt.setLabel("Cancelar");

        }
    }//GEN-LAST:event_btnEditarEntActionPerformed

    private void btnNuevaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSalidaActionPerformed
        // 

        if (btnNuevaSalida.getText().equals("Nueva")) {
            btnNuevaSalida.setLabel("Guardar");
            btnEditarSal.setLabel("Cancelar");
            btnEditarSal.setEnabled(true);
            txtCantidadSal.setText("");
            //txtFechaSal.setText("");
            Calendar actual = new GregorianCalendar();
            jDateFechaSal.setCalendar(actual);
            habilitarcamposSal();
            return;
        }

        mSalida datosSal = new mSalida();

        fGalpon func = new fGalpon();

        if (btnNuevaSalida.getText().equals("Guardar")) {

            if (jDateFechaSal.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Debes asignar una fecha de Salida");
                jDateFechaSal.requestFocus();
                return;
            }
            if (txtCantidadSal.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debes asignar una Cantidad");
                txtCantidadSal.requestFocus();
                return;
            }
            Date dateSal = jDateFechaSal.getDate();//almacena la fecha en formato Date
            long fechaS = dateSal.getTime();
            java.sql.Date fechaSal = new java.sql.Date(fechaS);//establece el formato compatible con sql
            datosSal.setIdGalpon(Integer.parseInt(lblNoGalpon.getText()));
            datosSal.setFecha(fechaSal.toString());
            datosSal.setCantidad(Integer.parseInt(txtCantidadSal.getText()));
            datosSal.setDescripcion(AtxtDescripcionSal.getText());
            datosSal.sethSaldo(Integer.parseInt(lblSaldo.getText()));

            func.insertarSalida(datosSal);

            //insertar(lblNoGalpon.getText(), "Salida");//envia el numero del galpon, envia el tipo de movimiento (entrada-salida)
            btnNuevaSalida.setLabel("Nueva");
            btnEditarSal.setLabel("Editar");
            txtCantidadSal.setText("");
            // txtFechaSal.setText("");
            deshabilitarcamposSal();

            frmGalpon(lblNoGalpon.getText());// para recargar el formulario
            return;

        }

        if (btnNuevaSalida.getText().equals("Actualizar")) {
            Date dateSal = jDateFechaSal.getDate();//almacena la fecha en formato Date
            long fechaS = dateSal.getTime();
            java.sql.Date fechaSal = new java.sql.Date(fechaS);//establece el formato compatible con sql
            datosSal.setIdGalpon(Integer.parseInt(lblNoGalpon.getText()));
            datosSal.setFecha(fechaSal.toString());
            datosSal.setCantidad(Integer.parseInt(txtCantidadSal.getText()));
            datosSal.setDescripcion(AtxtDescripcionSal.getText());
            datosSal.sethSaldo(Integer.parseInt(lblSaldo.getText()));
            datosSal.setIdSalida(Integer.parseInt(lblSalida.getText()));
            func.editarSalida(datosSal);

            // editar(lblNoGalpon.getText(), lblSalida.getText(), "salida");//envia el numero del galpon, envia el ID de la entrada
            btnNuevaSalida.setLabel("Nueva");
            btnEditarSal.setLabel("Editar");
            txtCantidadSal.setText("");
            // txtFechaSal.setText("");
            deshabilitarcamposSal();
            frmGalpon(lblNoGalpon.getText());
            // cantidad = 0;
            //saldoTotal = 0;
//        postsql.cierraConexion();

            mostrarEntrada(lblNoGalpon.getText());

            mostrarSalida(lblNoGalpon.getText());

        }

    }//GEN-LAST:event_btnNuevaSalidaActionPerformed

    private void btnEditarSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSalActionPerformed
        //
        if (btnEditarSal.getLabel().equals( "Cancelar")) {
            deshabilitarcamposSal();
            btnNuevaSalida.setLabel("Nueva");
            btnEditarSal.setLabel("Editar");
            btnEditarSal.setEnabled(false);
            jDateFechaSal.setCalendar(null);

        } else {
            habilitarcamposSal();
            btnNuevaSalida.setLabel("Actualizar");
            btnEditarSal.setLabel("Cancelar");

        }
    }//GEN-LAST:event_btnEditarSalActionPerformed

    private void tablaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEntradaMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha;

        int filaSel = tablaEntrada.rowAtPoint(evt.getPoint());

        try {
            //        jDateFecha.setDateFormatString(tablaEntrada.getValueAt(filaSel, 3).toString());
            fecha = formatoFecha.parse((String) tablaEntrada.getValueAt(filaSel, 3));
            jDateFechaEnt.setDate(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(frmGalpon.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtCantidadEnt.setText(tablaEntrada.getValueAt(filaSel, 4).toString());
        AtxtDescripcionEnt.setText(tablaEntrada.getValueAt(filaSel, 5).toString());
        lblEntrada.setText(tablaEntrada.getValueAt(filaSel, 6).toString());
        btnEditarEnt.setEnabled(true);
    }//GEN-LAST:event_tablaEntradaMouseClicked

    private void tablaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidaMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha;

        int filaSel = tablaSalida.rowAtPoint(evt.getPoint());
        try {
            //        jDateFecha.setDateFormatString(tablaEntrada.getValueAt(filaSel, 3).toString());
            fecha = formatoFecha.parse((String) tablaSalida.getValueAt(filaSel, 3));
            jDateFechaSal.setDate(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(frmGalpon.class.getName()).log(Level.SEVERE, null, ex);
        }
        //txtFechaSal.setText(tablaSalida.getValueAt(filaSel, 3).toString());
        txtCantidadSal.setText(tablaSalida.getValueAt(filaSel, 4).toString());
        AtxtDescripcionSal.setText(tablaSalida.getValueAt(filaSel, 5).toString());
        lblSalida.setText(tablaSalida.getValueAt(filaSel, 6).toString());
        btnEditarSal.setEnabled(true);
    }//GEN-LAST:event_tablaSalidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGalpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGalpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGalpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGalpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGalpon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AtxtDescripcionEnt;
    private javax.swing.JTextArea AtxtDescripcionSal;
    private javax.swing.JButton btnEditarEnt;
    private javax.swing.JButton btnEditarSal;
    private javax.swing.JButton btnNuevaEntrada;
    private javax.swing.JButton btnNuevaSalida;
    private com.toedter.calendar.JDateChooser jDateFechaEnt;
    private com.toedter.calendar.JDateChooser jDateFechaSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblGalpon;
    private javax.swing.JLabel lblNoGalpon;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JTable tablaEntrada;
    private javax.swing.JTable tablaSalida;
    private javax.swing.JTextField txtCantidadEnt;
    private javax.swing.JTextField txtCantidadSal;
    // End of variables declaration//GEN-END:variables
}
