/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Consultas.fProducto;
import Estilos.estiloTabla;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelos.mProducto;
import javax.swing.JFrame;

/**
 *
 * @author GIMORE
 */
public class frmProducto extends javax.swing.JInternalFrame {

    private Conexion postsql = new Conexion();
    private  Connection  cn = null; //variable de conexion de sql
    // private Connection cn = postsql.conectar();
    private String sSQL = "";//para almacenar cadena de conexion 
    public static String accion="";
 public static String [] datostabla={"","","","",""}; //vector para almacenar la informacion de la tabla
    /**
     * Creates new form frmProducto
     */
    public frmProducto() {
        initComponents();
          ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        mostrar("");
         jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
          estiloTabla diseño = new estiloTabla();
        diseño.tabla(tablaProducto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblidProducto = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(9, 66, 66));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRAR PRODUCTOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(268, 268, 268))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Unidad de Medida", "Descripcion", "Precio Unidad de Medida"
            }
        ));
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProducto);

        jPanel4.setBackground(new java.awt.Color(9, 66, 66));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(9, 66, 66));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/stockverde32px.png"))); // NOI18N
        jButton1.setText("STOCK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(9, 66, 66));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/searchblanco32px.png"))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BUSCAR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)))
                        .addGap(14, 14, 14))))
        );

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(9, 66, 66));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/editverde32px.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 66, 66)));
        btnEditar.setEnabled(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(9, 66, 66));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/deleterojo32px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 66, 66)));
        btnEliminar.setEnabled(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(9, 66, 66));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/addverde32px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 66, 66)));
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(9, 66, 66));
        jLabel4.setText("Lista de Productos Registrados");

        lblidProducto.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblidProducto)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
 
    public static void dimensioncols() {
        tablaProducto.getColumnModel().getColumn(0).setPreferredWidth(10);//ancho para la primer columna

       // tablaProducto.getColumnModel().getColumn(5).setPreferredWidth(15);//ancho para la primer columna
    }
    
    public  void mostrar(String buscar) { //para mostrar registros de la tabla galpon
        //DefaultTableModel modelo; //=(DefaultTableModel) tablaAdminGalpon.getModel(); // parte para obtener el modelo de tabla existente
        cn = postsql.conectar(); // asigna la cadena de conexion a la variable de conexion SQL

        if (cn == null) { // confirma si no hay conexion de la BD para no proceder con las consultas..
            JOptionPane.showMessageDialog(rootPane, " No se pueden  cargar Registros \n"
                    + " debido a un problema de Conexion a la BD. ");
            return;
        }

        try {
            DefaultTableModel modelo;
            fProducto func = new fProducto();
            modelo = func.mostrar(buscar);
            tablaProducto.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        dimensioncols();
        postsql.cierraConexion();
    }    // cierre de metodo

    private void habilitarcampos() {
        lblidProducto.setEnabled(true);
        /*txtNombre.setEnabled(true);
        txtUniMedida.setEnabled(true);
        AtxtDescripcion.setEnabled(true);
        txtPrecioUM.setEnabled(true);*/
    }

    private void deshabilitarcampos() {
        lblidProducto.setEnabled(false);
       /* txtNombre.setEnabled(false);
        txtUniMedida.setEnabled(false);
        AtxtDescripcion.setEnabled(false);
        txtPrecioUM.setEnabled(false);*/
    }

    private void limpiarCampos() {
        lblidProducto.setText("");
       /* txtNombre.setText("");
        AtxtDescripcion.setText("");
        txtUniMedida.setText("");
        txtPrecioUM.setText("");*/

    }


    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // 
        accion="nuevo";
         new Interfaz.DiagProducto(new JFrame(), true).setVisible(true);
       /* 
        if (btnNuevo.getText().equals("Nuevo")) {
            habilitarcampos();
            limpiarCampos();
            btnNuevo.setLabel("Guardar");
            btnNuevo.setIcon(new ImageIcon("src/Archivos/saveverde32px.png"));
            btnEditar.setLabel("Cancelar");
            btnEditar.setIcon(new ImageIcon("src/Archivos/cancelverde32px.png"));
            btnEditar.setEnabled(true);
            btnEliminar.setEnabled(false);
            txtNombre.requestFocus();
            return;
        }

        mProducto datos = new mProducto();
        fProducto func = new fProducto();

        if (btnNuevo.getText().equals("Guardar")) {
            // datos.setIdProducto(Integer.parseInt(lblidProducto.getText()));

            if (txtNombre.getText().equals("")) {//validar que se seleccione Ave
                JOptionPane.showMessageDialog(rootPane, "Debes asignar un nombre al producto");
                txtNombre.requestFocus();
                return;// para que salte y no siga el codigo
            }
            if (txtUniMedida.getText().equals("")) {//validar que se seleccione Ave
                JOptionPane.showMessageDialog(rootPane, "Debes asignar una Unidad de Medida");
                txtUniMedida.requestFocus();
                return;// para que salte y no siga el codigo
            }
            if (txtPrecioUM.getText().equals("")) {//validar que se seleccione Ave
                JOptionPane.showMessageDialog(rootPane, "Debes asignar una Precio a la Unidad de Medida");
                txtPrecioUM.requestFocus();
                return;// para que salte y no siga el codigo
            }
            datos.setNombre(txtNombre.getText());
            datos.setUniMedida(txtUniMedida.getText());
            datos.setDescripcion(AtxtDescripcion.getText());
            datos.setPrecioUniMed(Integer.parseInt(txtPrecioUM.getText()));
            validarDatoTipoNumero(txtPrecioUM.getText());
            if (func.insertar(datos)) {
                JOptionPane.showMessageDialog(rootPane, "Producto registrado Correctamente");
                mostrar("");
                deshabilitarcampos();
            }

            //insertar();
            limpiarCampos();
            deshabilitarcampos();
            btnNuevo.setLabel("Nuevo");
            btnNuevo.setIcon(new ImageIcon("src/Archivos/addverde32px.png"));
            btnEditar.setLabel("Editar");
            btnEditar.setIcon(new ImageIcon("src/Archivos/editverde32px.png"));
            btnEliminar.setEnabled(false);
            return;
        }
        if (btnNuevo.getText().equals("Actualizar")) {
            // datos.setIdProducto(Integer.parseInt(lblidProducto.getText()));
            datos.setNombre(txtNombre.getText());
            datos.setUniMedida(txtUniMedida.getText());
            datos.setDescripcion(AtxtDescripcion.getText());
            datos.setPrecioUniMed(Integer.parseInt(txtPrecioUM.getText()));
            datos.setIdProducto(Integer.parseInt(lblidProducto.getText()));
            if (func.editar(datos)) {
                JOptionPane.showMessageDialog(rootPane, "El Producto fue Editado satisfactoriamente");

            }
            mostrar("");
            postsql.cierraConexion();
            //editar(txtIdProducto.getText());
            limpiarCampos();
            deshabilitarcampos();
            btnNuevo.setLabel("Nuevo");
            btnNuevo.setIcon(new ImageIcon("src/Archivos/addverde32px.png"));
            btnEditar.setLabel("Editar");
            btnEditar.setIcon(new ImageIcon("src/Archivos/editverde32px.png"));
            btnEliminar.setEnabled(false);

         } */ 


    }//GEN-LAST:event_btnNuevoActionPerformed

    private void validarDatoTipoNumero(String dato) {
        int num;
        try {
            num = Integer.parseInt(dato);
            //JOptionPane.showMessageDialog(rootPane,"No se admiten letras en: ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se admiten letras en: ");
        }
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // 
        
      accion="editar";
        new Interfaz.DiagProducto(new JFrame(), true).setVisible(true);
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
   DiagEliminar advertencia = new DiagEliminar(new JFrame(), true);
        advertencia.lblTitulo.setText("ELIMINAR PRODUCTO");
        advertencia.AtxtAdvertencia.setText("Si elimina el PRODUCTO, la información correspondiente a"
                + "\n Ventas, Gastos, Producción y Estadísticas será  afectada.");
        advertencia.lblmsgConfirmar.setText("¿ Confirma que desea ELIMINAR el PRODUCTO ?  ");
        advertencia.setVisible(true);

 
if ( DiagEliminar.respuesta.equals("eliminar")){
     if (!lblidProducto.getText().equals("ID")) {//confirma  si esta seleccionado un registro
            fProducto func = new fProducto();
            mProducto datos = new mProducto();
           datos.setIdProducto(Integer.parseInt(lblidProducto.getText()));
          // int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Desea eliminar el producto?", "confirmar", 2);
            
               if (func.eliminar(datos)) {
                    JOptionPane.showMessageDialog(rootPane, "Producto Eliminado Correctamente");

               }
               //eliminar(Integer.parseInt(txtIdProducto.getText()));
               mostrar("");
               deshabilitarcampos();
               postsql.cierraConexion();
          
       } else {
           JOptionPane.showMessageDialog(rootPane, "No seleccionó ningun Registro");
       }

}
//       
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseClicked
        // TODO add your handling code here:
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        int filaSel = tablaProducto.rowAtPoint(evt.getPoint());
       
        
        datostabla[0]=tablaProducto.getValueAt(filaSel, 0).toString();//idproducto
        datostabla[1]=tablaProducto.getValueAt(filaSel, 1).toString();//nombre
        datostabla[2]=tablaProducto.getValueAt(filaSel, 2).toString();//unidad de medida
        datostabla[3]=tablaProducto.getValueAt(filaSel, 3).toString();//descripcion
        datostabla[4]=tablaProducto.getValueAt(filaSel, 4).toString();//precio unidad de medida
        
        
       lblidProducto.setText(datostabla[0]);
/*        txtNombre.setText(tablaProducto.getValueAt(filaSel, 1).toString());
        txtUniMedida.setText(tablaProducto.getValueAt(filaSel, 2).toString());
        AtxtDescripcion.setText(tablaProducto.getValueAt(filaSel, 3).toString());
        txtPrecioUM.setText(tablaProducto.getValueAt(filaSel, 4).toString());*/
    }//GEN-LAST:event_tablaProductoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmStock form = new frmStock();
               int ancho = frmInicio.escritorio.getWidth();
            int altura = frmInicio.escritorio.getHeight();
            form.setSize(ancho, altura);
            frmInicio.escritorio.add(form);
            form.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        mostrar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblidProducto;
    public static javax.swing.JTable tablaProducto;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
